In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.3'

In [3]:
one_d = np.array([1,2,3,4.4], dtype='complex')

In [4]:
print("Data inside the array is:- ",one_d)
print("Dimanesion is:- ",one_d.ndim)
print("Datatype is:- ",one_d.dtype)
print("Shape is:- ",one_d.shape)
print("Size is:- ",one_d.size)

Data inside the array is:-  [1. +0.j 2. +0.j 3. +0.j 4.4+0.j]
Dimanesion is:-  1
Datatype is:-  complex128
Shape is:-  (4,)
Size is:-  4


In [5]:
two_d = np.array([[1,2,3],[4,5,6],[23,32,45]])

In [6]:
print("Dimanesion is:- ",two_d.ndim)
print("Datatype is:- ",two_d.dtype)
print("Shape is:- ",two_d.shape)
print("Size is:- ",two_d.size)

Dimanesion is:-  2
Datatype is:-  int64
Shape is:-  (3, 3)
Size is:-  9


In [7]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [8]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [9]:
np.arange(10,20,-2)

array([], dtype=int64)

In [10]:
np.arange(20,10,-2)

array([20, 18, 16, 14, 12])

In [11]:
np.arange(20,9,-2)

array([20, 18, 16, 14, 12, 10])

In [12]:
np.linspace(10,-20,5)

array([ 10. ,   2.5,  -5. , -12.5, -20. ])

In [13]:
aa = np.array([1,2,5])

In [14]:
aa.reshape(-2,1).shape

(3, 1)

In [15]:
aa.mean()

2.6666666666666665

In [16]:
np.nan

nan

In [17]:
bb = np.array([1,2,3])

In [18]:
bb

array([1, 2, 3])

In [19]:
bb.var() == np.power(bb.std(),2)

True

In [20]:
bb.sum()

6

In [21]:
bb.argmax()

2